apiVersion: v1
kind: Service
metadata:
  name: dco-api-service
  namespace: dco-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: dco-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
